### PR TITLE
Feature/allow insecure tls and fix component upgrade in other namespaces

### LINKED ISSUE #35: fix missing component upgrade when component has a set deployNamespace
Please fix a missing component upgrade when the component has a set `deployNamespace` in its CR. Currently there is just one component that is affected by this (which also is only installed and barely upgraded): 

github.com/cloudogu/k8s-longhorn

### PR DESCRIPTION
**Pull request by meiserloh**
Resolves #35 & #36

### CODE REVIEW

File: pkg/config/config.go [hunk 1]
```diff
@@ -60,7 +61,8 @@ type HelmRepositoryData struct {
 	// Schema describes the way how clients communicate with the Helm registry endpoint.
 	Schema EndpointSchema `json:"schema" yaml:"schema"`
 	// PlainHttp indicates that the repository endpoint should be accessed using plain http
-	PlainHttp bool `json:"plainHttp,omitempty" yaml:"plainHttp,omitempty"`
+	PlainHttp   bool `json:"plainHttp,omitempty" yaml:"plainHttp,omitempty"`
+	InsecureTLS bool `json:"insecureTls" yaml:"insecureTls"`
```
Comment (kahoona77) [inline pkg/config/config.go:65]:
```suggestion
        // InsecureTls allows invalid or selfsigned certificates to be used. This option may be overridden by PlainHttp which forces HTTP traffic.
	InsecureTLS bool `json:"insecureTls" yaml:"insecureTls"`
```

File: pkg/helm/client/client_test.go [hunk 2]
```diff
@@ -56,19 +56,46 @@ func TestNewClientFromRestConf(t *testing.T) {
...
+		// when
+		err := setEnvSettings(options, settings)
+
+		// then
+		require.NoError(t, err)
+		assert.Equal(t, "asdf", settings.RepositoryConfig)
+		assert.Equal(t, "asdf", settings.RepositoryCache)
+		assert.Equal(t, true, settings.Debug)
+		assert.Equal(t, "asdf", settings.RegistryConfig)
+	})
```
Comment (kahoona77) [inline pkg/helm/client/client_test.go:98]:
```suggestion
	t.Run("should not initialize existing options object", func(t *testing.T) {
		// given
		settings := &cli.EnvSettings{}
		options := &Options{
			Namespace:        "anamespace",
			RepositoryConfig: "arepoconfig",
			RepositoryCache:  "arepocache",
			Debug:            true,
			DebugLog:         func(format string, v ...interface{}) {},
			RegistryConfig:   "aregconfig",
			Output:           nil,
			PlainHttp:        true,
			InsecureTls:      true,
		}

		// when
		err := setEnvSettings(options, settings)

		// then
		require.NoError(t, err)
		assert.Equal(t, "arepoconfig", settings.RepositoryConfig)
		assert.Equal(t, "arepocache", settings.RepositoryCache)
		assert.Equal(t, true, settings.Debug)
		assert.Equal(t, "aregconfig", settings.RegistryConfig)
	})
```

File: pkg/logging/logger.go [hunk 3]
```diff
@@ -25,7 +25,10 @@ const (
 
 // CurrentLogLevel is the currently configured logLevel
 // The default logLevel is "ERROR"
```
Comment (kahoona77) [inline pkg/logging/logger.go:27]:
```suggestion
```
