### PR TITLE
Reset component status

### LINKED ISSUE #51: Reset component status in error case
If a component fails to update it remains in the `upgrading` status and changes to the spec won't be reconciled.
Furthermore the helm rollback is buggy.

### PR DESCRIPTION
**Pull request by nhinze23**
Requeue CRs on failures. This resets the status so that the CRs can be modified and reconciled again.
Add 3 Additional status phases for installing, upgrading, and deleting to identify the state of a CR in reconcile mode. This should be used determining the health of a component. In reconcile with new status phases the component is not healthy.

Resolves #51

### CODE REVIEW

File: pkg/controllers/componentDeleteManager.go [hunk 1]
```diff
@@ -31,12 +31,12 @@ func (cdm *componentDeleteManager) Delete(ctx context.Context, component *k8sv1.
...
 	component, err := cdm.componentClient.UpdateStatusDeleting(ctx, component)
 	if err != nil {
-		return fmt.Errorf("failed to update status-deleting for component %s: %w", component.Spec.Name, err)
+		return &genericRequeueableError{fmt.Sprintf("failed to update status-deleting for component %s", component.Spec.Name), err}
 	}
 
 	deployedReleases, err := cdm.helmClient.ListDeployedReleases()
 	if err != nil {
-		return fmt.Errorf("could not list deployed Helm releases")
+		return &genericRequeueableError{fmt.Sprintf("could not list deployed Helm releases"), err}
```
Comment (cesmarvin) [inline pkg/controllers/componentDeleteManager.go:39]: 🚫 **[checkstyle]** <gosimple> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>S1039: unnecessary use of fmt.Sprintf

**Review by jelemux — APPROVED** [review]
LGTM!
